### ISSUE TITLE
Missing extensio.previewSwagger file

### ISSUE THREAD

**Issue by newportg** [arjun-g/vs-swagger-viewer#10]
Whenever I download the previewSwagger file is missing :(

**Comment by arjun-g** [comment]
Hi,

I couldn't understand the issue properly. Can you please elaborate a little more. Some kind of screenshot would be helpful in understanding.

Thank you.

**Comment by newportg** [comment]
Hi,
I've tried to download your plugin several times, and every time the extension.previewSwagger file is missing, so I'm unable to view the swagger file.

Thanks

**Comment by cp16net** [comment]
I just got the same issue when using a new untitled (not saved) window. After i saved the file as `swagger.yml` the preview worked.
