### ISSUE TITLE
Doesn't allow for multiple Swagger docs to be open

### ISSUE THREAD

**Issue by cdstrachan** [arjun-g/vs-swagger-viewer#11]
If I have two different swagger docs open in Visual Studio, the preview for both docs shows the same preview - the first document opened.

Have a look at the attachment. The left image is correct. The right is not (all fine except for the swagger contents
).
![screen shot 2017-04-11 at 10 59 53 am](https://cloud.githubusercontent.com/assets/25429862/24901157/772856d4-1ea6-11e7-9751-54e7461352cd.png)

**Comment by arjun-g** [comment]
Fixed in v2.0.0
