### ISSUE TITLE
Switch to Swagger Editor 3.x

### ISSUE THREAD

**Issue by fmauNeko** [arjun-g/vs-swagger-viewer#13]
Hello,

Swagger Editor has released a new major revision, 3.x, which has been rebuilt from the ground up and has better performance and look-and-feel.

I tried to edit it myself, but as I couldn't find any documentation about the edits you've done onto the original Swagger Editor, I didn't have any success.

Thanks in advance, and have a good day !

**Comment by darinkrauss** [comment]
What would be required for supporting Open API 3.x?

**Comment by fmauNeko** [comment]
Switching to Swagger Editor 3.1+

**Comment by darinkrauss** [comment]
Is that something I can help with? If so, do you have any documentation/notes about how to switch? I diff'd the `static` directory of this repo against the `2.x` branch of the swagger-editor repo, but had trouble nailing the specific swagger-editor commit, plus there were a bunch of line-ending changes (multi-line files to single-line, particularly for the `templates` directory) that made diff'ing difficult.

**Comment by fmauNeko** [comment]
That's why I gave up, there are too many changes from the original stuff and I didn't have the time/motivation to continue investigating it.

**Comment by jienco** [comment]
Hi! I submitted a PR which updates to Swagger UI v3 and adapts the extension to work with it with JSON and YAML files, keeps reloading the file on changes (just like it was).

**Comment by mateuscb** [comment]
@jienco that commit looks good! Hopefully they get it merged in there soon. Thanks!

**Comment by jienco** [comment]
Thank you very much @mateuscb :) I am looking forward to use the extension with Swagger v3 in vscode.

**Comment by arjun-g** [comment]
Sorry for the delayed response guys. I got caught up in some work. Thank you @jienco you PR is merged and extension is updated as well.

**Comment by jienco** [comment]
Thank you very much @arjun-g :)
