### ISSUE TITLE
This still requires active internet connection right?

### ISSUE THREAD

**Issue by rosdi** [arjun-g/vs-swagger-viewer#15]
I downloaded this because I assumed this is an offline tool so that I can work on my swagger API offline. But it seems to be connecting to swagger.io to preview the files... am I right?

If that is the case it does not add any value... I might as well you editor.swagger.io directly from Chrome.

**Comment by megakilo** [comment]
You can totally use swagger-viewer offline. The preview is hosted locally.

**Comment by arjun-g** [comment]
@rosdi as @megakilo mentioned this works offline. If you face any issue while using it offline please do inform.
