### ISSUE TITLE
Errors do not go away when problem is resolved

### ISSUE THREAD

**Issue by KahunaCode** [arjun-g/vs-swagger-viewer#16]
When an error is noted and then fixed, the error still populates the live preview. Refreshing causes it to go away, but it isn't working in the live update.

**Comment by d4nyll** [comment]
I think this is a problem with Swagger Editor itself, as I get the same issue using Swagger Editor on its own.

**Comment by arjun-g** [comment]
@KahunaCode check the current version of the extension as it is updated with the new Swagger UI v3 and I hope it is fixed.
