### ISSUE TITLE
Swagger files with *.yml extension doesn't work

### ISSUE THREAD

**Issue by mikekolganov** [arjun-g/vs-swagger-viewer#18]
`swagger.yaml` works, `swagger.yml` — just white screen. See screenshots below:

![2017-12-20_18-21-27](https://user-images.githubusercontent.com/557480/34207159-7ab426f0-e5b3-11e7-9ba1-7bed989d8de0.png)

![2017-12-20_18-21-54](https://user-images.githubusercontent.com/557480/34207162-7c7a80e2-e5b3-11e7-9a1a-df6f47377f5a.png)

**Comment by LaPoPvLe** [comment]
thx
now i know what's wrong with my sw previewer

**Comment by Gabology** [comment]
Having the same issue here, I do believe that it used to work before..

**Comment by iamlothian** [comment]
I get the same issue but for `*.yaml` but not for `*.json`

**Comment by arjun-g** [comment]
Should be fixed in the latest version. Please check.
