### ISSUE TITLE
Unable to Parse: Missing error

### ISSUE THREAD

**Issue by pj035** [arjun-g/vs-swagger-viewer#20]
Hey guys,

if I open the swagger viewer in VS Code the page remains empty/white. Opening the dev tools reveals the message: `ERR Unable to parse.` Without a useful hint I am not able to debug.

The swagger online editor shows no error.

Note: I'm using open api specification 3.0.1. Might this be a problem?

Extension Version: 1.5.0

EDIT: Unfortunately I can not post the .yaml file because it's an internal api that is not meant for the public (yet).

**Comment by arjun-g** [comment]
Should be fixed in the latest version. Please check.
