### ISSUE TITLE
Preview displaying as blank

### ISSUE THREAD

**Issue by dbfr3qs** [arjun-g/vs-swagger-viewer#22]
Hi there, I have a 300 line swagger file which is displaying as a blank vscode tab. Any suggestions as to why this may be the case?

![image](https://user-images.githubusercontent.com/8849021/35885925-4fe6afa8-0bf4-11e8-8c61-07b054230455.png)

Running OSX 10.12.6. The swagger file loads perfectly at editor.swagger.io without any errors.

**Comment by particle6** [comment]
I am also seeing this issue

**Comment by arcotek-ltd** [comment]
Same issue as @dbfr3qs. The file is *.yaml (not *.yml), exported from Swaggerhub. Also tried with the same code, exported as JSON. Both result in blank previews.

Preview works in swaggerhub.

**Comment by dbfr3qs** [comment]
Yep, that works for me - renaming the file to .yaml. I feel a little bit silly that it was such a simple thing but glad to see the PR with a minor fix to support .yml.

**Comment by paulcarroll** [comment]
+1 rename yml to yaml worked for me too

**Comment by fastreles** [comment]
For me (on MacOS) it seems to work for a while, and then stop. Then it won't work again until restarting vscode. The result is the same regardless of whether viewing in vscode or in the browser.

**Comment by SylwesterZarebski** [comment]
I have also blank window when trying to preview on freshly created tab - without saving file.

**Comment by iamlothian** [comment]
If i debug the browser window it opens, I can see that sometimes the socket.io events are not being triggered. Could be a synchronous issue, i haven't dug into the code too far.

**Comment by nplatis** [comment]
Preview is blank for me as well. VSCode 1.22.2 on Linux.
If I try to preview on external browser, I receive "Connection refused" error message.

**Comment by taku-arakaki** [comment]
In Swagger Viewer 1.6.0, I also blanked out the preview.
When I tried it with 1.7.0 from GitHub, the problem was solved.

Please update Marketplace version from 1.6.0 to 1.7.0.

**Comment by imolloy** [comment]
I'm still seeing black previews on 1.7.0 on macOS 10.13.4.

**Comment by cpheps** [comment]
Also, seeing black previews on 1.7.0 on macOS 10.13.5. This was working a week ago on the same file not sure what has changed. I'm also using vscode Insiders

**Comment by alexwbaule** [comment]
For me too,  it seems to work for a while, and then stop. Then it won't work again until restarting vscode. The result is the same regardless of whether viewing in vscode or in the browser.

**Comment by taku-arakaki** [comment]
It works well in the following environment on Windows7 and Linux(CentOS7).

vscode version 1.24.0
Swagger Viewer v.1.7.0

**Comment by scislaghi** [comment]
I started to experience the same issue. 
VSC 1.24.1 
Swagger Viewer 1.7.0
macOS 10.12.6

Renaming from YML to YAML didn't work.

**Comment by scislaghi** [comment]
@arjun-g I pulled the new extension.js as result of pull #32 and tested it, but it's not solving the problem. Is there a way to debug it?

**Comment by andfinally** [comment]
I tried my file in the [Swagger editor](https://editor.swagger.io/), which told me it had no `paths` defined. When I added them in the preview started working - so one thing to do is check for errors in the file.

**Comment by sudheerah** [comment]
Had the same issue. Tried after saving the file as yml and worked.

**Comment by tahir-pasha** [comment]
didn't work for me.
