### ISSUE TITLE
Blank/white screen with *.json; *.yaml works fine

### ISSUE THREAD

**Issue by isawch** [arjun-g/vs-swagger-viewer#26]
Hi,

As of the latest update, I've found none of my *.json swagger files will preview in the tab/browser, whereas the exact same version in *.yaml  works fine.

I've tested the json version of my swagger files on the swagger.io site and they render fine.  Even exporting those same json files as yaml and previewing in the plugin in VSC also works fine.  It just seems there is something wrong/different with the JSON rendering.

Would love some suggestions on how to correct this -- i find this plugin to be an incredibly useful tool and saves a huge amount of time.

**Comment by aqdaniels-nm** [comment]
Came here looking for solutions.  I'm also getting the blank preview screen for .json swagger doc

**Comment by arjun-g** [comment]
Fixed in #27
