### ISSUE TITLE
Swagger preview changes versions

### ISSUE THREAD

**Issue by matthewknights** [arjun-g/vs-swagger-viewer#28]
Hi, 
I have used the online swagger editor which allows you chose between the new and old versions.  I recently installed the vscode plugin which has been really useful. I've noticed that the preview appears to change between the versions of the editor.  Usually when I first open vscode it will show the preview is in the latest version, then after some changes it will change to the older version.  I can't quite pick out anything specifically that has triggered this behavior.  Is there a way to force a specific version of the preview? 

Regards

**Comment by arjun-g** [comment]
Latest version will not have this issue
