### ISSUE TITLE
LOCAL WEB SERVER NOT WORKING TIME TO TIME

### ISSUE THREAD

**Issue by liguori** [arjun-g/vs-swagger-viewer#33]
Hello,
i am using the preview in browser with the setting:
`"swaggerViewer.previewInBrowser": true,`

At the beginning is working very good but sometime (very often and i don't know when exactly) it look like the local web serve that hosts the Swagger UI stops to work.

This is the errore that i get from by browser
ERR_CONNECTION_REFUSED

I try to give again the command "Preview Swagger" but it doesn't work.

I have to restart VS Code for make it working.

**Comment by arjun-g** [comment]
Give it a try now in the latest version. Some changes has been done on this.

**Comment by liguori** [comment]
Hello @arjun-g, it look like now is working very good, very stable and changes are real time (i don't have to save the file for preview it).
Congratulation about the work has done on this release :)
