### ISSUE TITLE
"swagger: 2.0" is not recognized as a supported version field

### ISSUE THREAD

**Issue by bvandenbogaard** [arjun-g/vs-swagger-viewer#39]
When specifying the version field, the viewer doesn't allow 2.0 without quotation:

swagger: 2.0 <-- triggers a "Unable to render this definition"
swagger: "2.0" <-- works

Both are valid Swagger syntax.

**Comment by arjun-g** [comment]
I don't think so. As per the specification this should be a string - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields
