### ISSUE TITLE
Option to disable "Preview Done" notification

### ISSUE THREAD

**Issue by riesinger** [arjun-g/vs-swagger-viewer#40]
While I love this extension, the "PREVIEW DONE" notification is quite obnoxious and annoying. 
Especially since it has a red cross hinting that there was an error, being written in all caps and me having to click it to go away.

Therefore, I think there should be an option to turn this notification off.

![image](https://user-images.githubusercontent.com/6919894/43722658-108b4636-9996-11e8-9ed6-c8bf779fe020.png)

Thanks a lot!

**Comment by arjun-g** [comment]
Ahh this was a message I added for checking something. Thanks for pointing out. Removed and pushed a new version.
