### ISSUE TITLE
The request body disappears when the model is live updated

### ISSUE THREAD

**Issue by fungiboletus** [arjun-g/vs-swagger-viewer#43]
The request body disappears when the model is live updated.

## How to reproduce

Use the following model and preview it in swagger-viewer. Expand the /test method, it contains a form for the requestBody.
Update the model (add a letter in the summary for example). The form has disappeared.

```yaml
openapi: 3.0.0
info:
  title: test
  version: "1.0.0"

paths:
  /test:
    post:
      summary: Test request body
      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ttl:
                  type: number
                  format: int64
      responses:
        "204":
          description: "ok"

```

**Comment by polarweasel** [comment]
Can confirm this is reproducible, with this and with my own OAS 3 spec.

**Comment by polarweasel** [comment]
Is this related to [swagger-parser issue 765](https://github.com/swagger-api/swagger-parser/issues/765)? If so, a new build might resolve this one.

**Comment by thattolleyguy** [comment]
Any update on this issue? Thanks

**Comment by osdiab** [comment]
I too am experiencing this.
