### ISSUE TITLE
Preview pane only shows "Access Denied"

### ISSUE THREAD

**Issue by ringods** [arjun-g/vs-swagger-viewer#46]
When resurrecting an old project containing a swagger file, I installed the Swagger Viewer extension for the first time. I reloaded VSCode after installation, then triggerd the `Preview Swagger` action on the open `swagger.yaml` file. But the only thing I see in the preview pane is this:

```
AccessDeniedAccess Denied./18264904933L1373L137
```

Any idea what is wrong?

VSCode 1.26.1
Swagger Viewer 2.0.2
MacOS High Sierra 10.13.6

**Comment by paulcram** [comment]
I had the same problem.  In my case, I already had something listening on port 9000 (minio).  I fixed it by changing the default port in the VS Code user settings for the swagger editor to 9001, then restarted VS Code.

**Comment by arjun-g** [comment]
Fixed in 3.0.0. Will auto assign next available port for preview.
