### ISSUE TITLE
Validator is too aggressive

### ISSUE THREAD

**Issue by hendrix04** [arjun-g/vs-swagger-viewer#47]
The swagger validator attempts to validate any json file with a top level key of swagger even if it isn't a swagger file. This leads to problems popping up in the problem list when they shouldn't.

**Comment by jmcdo29** [comment]
Same problem as hendrix04, my package.json in a node.js project is being validated by the validator and is showing a problem even though this is not a valid swagger file at all. Can we do something about this?

**Comment by varshard** [comment]
It also did the same with yml files as well.

**Comment by kazazor** [comment]
To me it's happening on yml file even if the top level key does not belong to the OAS.

This is really annoying :/

**Comment by arjun-g** [comment]
Fixed in 3.0.0.
