### ISSUE TITLE
$ref path handling problematic

### ISSUE THREAD

**Issue by n-alex-white** [arjun-g/vs-swagger-viewer#52]
I have the following reference in my YAML file

              schema:
                $ref: '../schema/customer-address-v1.yaml#/components/schemas/Address'

But the swagger viewer thinks that this is an improper path, and it is looking for the referenced file here

      Error opening file "users/alex/sites/work/schema/customer-address-v1.yaml"

It should be looking in 

    users/alex/sites/work/{project}/customer/profile/schema/customer-address-v1.yaml

Other applications like swagger-cli correctly use the relative path reference in my YAML file, but swagger-viewer does not (which renders swagger viewer problematic)

This is on a Mac, in case that is significant. 

I note that internally your extension uses the open source swagger-parser, and when I use that (or swagger-cli, which uses it), then there is no problem with the reference handling.

**Comment by hatakawas** [comment]
+1

**Comment by arjun-g** [comment]
Hey devs, very sorry for the delayed response. Will try to push a fix for this by this week.

**Comment by arjun-g** [comment]
Will be tracked in #45
