### ISSUE TITLE
Are all dependencies included?

### ISSUE THREAD

**Issue by bardware** [arjun-g/vs-swagger-viewer#55]
Hi,

I just like to know if all dependencies are included or if my data are being posted to some service and converted to HTML, there.

Best,
Bernhard

**Comment by yuri1969** [comment]
The HTML preview should be simply generated using [swagger-ui](https://github.com/swagger-api/swagger-ui/) lib. Check their implementation.

**Comment by arjun-g** [comment]
Everything happens in your system
