### ISSUE TITLE
Missing path variable error is not visible

### ISSUE THREAD

**Issue by jmcanache** [arjun-g/vs-swagger-viewer#76]
Here is a small example code where the path variable is not defined: 

`/users/{id}/test:
    post:
      tags:
      - "Test"
      operationId: "userTest"
      responses:
        200:
          description: "Operation good!"
         ....`

In the official swagger page(https://editor.swagger.io/) I can see this type of errors but inside vs there is no notifications

**Comment by arjun-g** [comment]
Should be fixed in 3.0.0
