### ISSUE TITLE
Swagger examples support

### ISSUE THREAD

**Issue by skryvets** [arjun-g/vs-swagger-viewer#78]
OAS 2 and 3 supports [_examples_](https://swagger.io/docs/specification/2-0/adding-examples/) where you can see request/response samples, illustrate different options for query params and other possibilities. 

Here's screenshot that demonstrates UI dropdown to select from

https://user-images.githubusercontent.com/1156160/60561206-b68aa580-9d8d-11e9-9c3f-4b1a83ab895d.png

Are there any plans to support it? I utilize it heavily in my projects. Thank you.

**Comment by JSchoreels** [comment]
Looks like it needs to use UI version >= 3.23 (https://swagger.io/docs/specification/adding-examples/)

Dependencies are : 
		"swagger-ui-dist": "^3.22.0"

**Comment by bruha** [comment]
While MR is waiting to be merged, you can bump "swagger-ui-dist" version locally:
run in terminal
`$ cd ~/.vscode/extensions/arjun.swagger-viewer-2.2.2`
`$ nano package.json`
change
`"swagger-ui-dist": "^3.22.0",`
to
`"swagger-ui-dist": "^3.25.0",`
run
`$ npm i`

Observe Swagger examples 😎

**Comment by arjun-g** [comment]
Fixed in version 3.0.0. swagger-ui-dist upgraded to 3.25.2
